-- Words-mode passages long enough for every words-test length.
--
-- A words test types the first `wordCount` words of its passage (limitToWords
-- in src/features/typing/lib/wordLimit.ts), and a shorter passage ends the test
-- early. The NORMAL English passages were 24-48 words long, so 50, 100 and
-- 200 word tests could never reach their target. Session creation now serves a
-- words test only a passage with at least that many words.
--
-- The text is the en-long-* entries of englishPassages in
-- src/features/typing/lib/passages.ts, which also seeds new databases.
-- tests/unit/wordsModePassages.test.ts keeps this file identical to it.
-- Data only: no schema change.

-- Correct the stored word counts of NORMAL English passages. They were
-- entered by hand and overstated (for example 50 for a 48-word passage).
-- Words are counted as limitToWords cuts them: spaces + 1.
UPDATE "passages"
SET "wordCount" = CASE WHEN "content" = '' THEN 0 ELSE char_length("content") - char_length(replace("content", ' ', '')) + 1 END
WHERE "mode" = 'NORMAL' AND "language" = 'ENGLISH' AND "wordCount" <> CASE WHEN "content" = '' THEN 0 ELSE char_length("content") - char_length(replace("content", ' ', '')) + 1 END;

-- Add the long passages. Idempotent: text that is already present is skipped.
INSERT INTO "passages" ("id", "content", "language", "category", "difficulty", "mode", "wordCount", "charCount", "isActive")
SELECT gen_random_uuid(), v."content", 'ENGLISH'::"Language", v."category", 'INTERMEDIATE'::"Difficulty", 'NORMAL'::"PassageMode", v."wordCount", v."charCount", true
FROM (VALUES
    ('Learning to type well is less about speed and more about rhythm. When you first sit down at a keyboard, every letter feels like a small search, and your eyes jump between the screen and your hands. With steady practice, that search fades away. Your fingers learn where each key lives, and the words begin to flow without conscious effort. The secret is to slow down at the start. Typing accurately at a gentle pace builds the right habits, while rushing tends to lock in mistakes that are hard to unlearn later. Keep your wrists relaxed and your shoulders loose, and let your fingers return to the home row after each stroke. Short sessions every day are far more useful than one long session each week, because the brain needs time to turn practice into memory. It also helps to type real sentences rather than random letters, since everyday writing contains the patterns you will use most often. Over time you will notice that common words like the, and, and that seem to type themselves. When that happens, you can gradually raise your pace and focus on the words that still slow you down. Progress may feel slow from one day to the next, but over a few weeks the improvement is often remarkable. Patience and consistency are what turn a careful beginner into a fluent typist.', 'common', 227, 1279),
    ('Every successful project begins with a clear understanding of the problem it is meant to solve. Before a team writes a plan or sets a deadline, it should agree on who the work is for, what those people need, and how everyone will know when the job is done. This early conversation can feel slow, but it saves a great deal of time later, because it prevents the team from building the wrong thing well. Once the goal is clear, the work can be divided into small pieces that each deliver something useful on their own. Small pieces are easier to estimate, easier to review, and easier to change when new information arrives. Regular check-ins keep everyone aligned, and a short written summary after each meeting makes sure that decisions are not forgotten. Good teams also plan for risk. They ask what could go wrong, how likely it is, and what they would do if it happened. A simple list of risks, reviewed every few weeks, turns unpleasant surprises into problems the team has already discussed. Finally, a project is not finished when the last task is closed. The team should look back on what went well and what did not, and share those lessons openly. Honest reflection is how a group of capable individuals slowly becomes a truly effective team.', 'business', 221, 1250),
    ('When you open a website, a surprising amount of work happens in less time than it takes to blink. Your browser first asks a name server to translate the address you typed into a numeric location on the network. It then opens a secure connection to that server, agreeing on encryption keys so that nobody in between can read or change the data. Next, the browser requests the page, and the server replies with a document written in a markup language that describes its structure. That document usually points to other files, such as style sheets that control colors and layout, scripts that add interactive behavior, and images that fill the screen. The browser fetches each of these, often several at once, and begins to build a model of the page in memory. It calculates where every element should appear, paints the pixels, and runs the scripts, which may request even more data in the background. Caching makes later visits much faster, because files that have not changed can be loaded from local storage instead of the network. Developers measure all of these steps carefully, since a delay of even a fraction of a second can cause visitors to leave. Understanding this journey helps engineers find the slow parts and build pages that feel instant to the people who use them.', 'technical', 221, 1280),
    ('Cities are often described as crowded and loud, yet many of them hide quiet places that reward anyone willing to explore on foot. A walk through an old neighborhood can reveal narrow lanes, small gardens behind iron gates, and buildings whose stone walls have watched several centuries pass. Early in the morning, before the traffic builds, you can hear birds in the trees and the soft sounds of shops opening for the day. Bakers pull fresh bread from their ovens, and the smell drifts out onto the street. Walking slowly lets you notice details that are invisible from a car or a bus, such as painted tiles above a doorway, a carved date on a bridge, or a tiny park where neighbors meet to talk. Many cities now protect these spaces by closing some streets to cars, planting new trees, and building wide paths for people on foot and on bicycles. These changes make the air cleaner and the streets safer, and they encourage people to spend more time outdoors. A regular walk is also good for health, since it strengthens the heart and clears the mind. The next time you have an hour to spare, leave the map at home, choose a direction, and let the city show you something new.', 'common', 212, 1176),
    ('Software testing is the practice of checking that a program does what it is supposed to do, and that it keeps doing so as the code changes over time. The simplest tests, often called unit tests, examine one small function at a time. They give the function a known input and confirm that it returns the expected output. Because they are small and fast, a project can run thousands of them in a few seconds after every change. Integration tests go one step further and check that several parts of a system work correctly together, such as a web service and the database it depends on. These tests are slower, but they catch problems that unit tests cannot see, like a query that fails only on a real database. End-to-end tests drive the finished application the way a person would, clicking buttons and filling in forms in a real browser. A healthy project uses all three kinds in sensible proportions, with many quick unit tests and fewer slow end-to-end tests. Good tests are clear about what they check, independent of one another, and reliable enough that a failure always means something. When a bug is found in production, a careful team first writes a test that reproduces it, then fixes the code, so the same mistake can never quietly return.', 'technical', 220, 1248)
) AS v("content", "category", "wordCount", "charCount")
WHERE NOT EXISTS (SELECT 1 FROM "passages" p WHERE p."content" = v."content");
