// PRIVACY_POLICY.md from the operator's legal pages pack (9 October 2026), verbatim.
// A working draft: see LEGAL_PAGES_DRAFT in ../legalPages.ts before publishing.
// Rendered by parseLegalMarkdown: headings, paragraphs (each line break kept),
// lists, **bold**, *italic* and --- only.
export const PRIVACY_POLICY = `# TypeFlow Privacy Policy

**Last updated: 9 October 2026**

This Privacy Policy explains how **Digvijay Bhota, operator of TypeFlow** (“TypeFlow”, “we”, “us” or “our”) collects, uses, shares, retains and protects information when you use the TypeFlow website and services.

TypeFlow is operated by an individual and is not represented as a separately incorporated company.

**Privacy contact:** xvshad585@gmail.com
**Correspondence address:** 266, White City, near Rai Farms, Sector 114, Mohali, Punjab, India. *(Confirm the full postal address and PIN code before publication.)*

## 1. Scope

This Policy covers TypeFlow accounts, typing tests and results, certificates and verification, Pro subscriptions, support requests, and organisation/assessment features. A third-party organisation that invites you to an assessment may also process your information under its own privacy notice and instructions.

## 2. Information we process

The information processed depends on which features you use. It may include:

### Account and identity information

- name or display name;
- email address and account identifiers;
- authentication, account status and security-related records; and
- information you send to customer support.

### Typing activity and results

- test or assessment selected, attempt status, timestamps and duration;
- performance results such as words per minute, accuracy, word count and other metrics shown in the product;
- input, timing or typing-trace information where the relevant feature records it for result validation, troubleshooting, security or abuse prevention; and
- disqualification, plausibility, audit or review records where generated by the Service.

Typing results are server-verified but unproctored. Technical plausibility checks do not prove that a particular individual completed a test without assistance.

### Certificates and verification

- certificate identifiers, issue dates, associated results and verification status;
- information needed to generate a certificate; and
- information displayed on a certificate’s QR or online verification page.

A person who receives a certificate or its verification link may be able to view the certificate information made available on that page. Consider this before sharing a certificate publicly.

### Assessment and organisation information

Where an organisation uses TypeFlow, we may process candidate names, email addresses, invitations, assessment identifiers, attempt status, results and other information supplied by the organisation or participant. The organisation may decide why the assessment is conducted and how its results are used.

### Payment and subscription information

We may receive plan identifiers, subscription identifiers, payment/order references, amount, currency, payment status, invoice references, billing dates, cancellation status, refund status, and webhook/event records from the payment provider. Payment card, bank, UPI or mandate credentials are handled by the payment provider. Do not send full payment credentials or one-time passcodes to TypeFlow support.

### Technical and security information

Our hosting, authentication and security systems may produce IP addresses, request timestamps, browser/device information, error reports, rate-limit events, audit records, and related request metadata. We use this information for authentication, availability, troubleshooting, fraud prevention, security and abuse investigation.

## 3. How we use information

We use information, as permitted by applicable law, to:

1. create and secure accounts and authenticate users;
2. run tests and assessments and calculate, validate or display results;
3. issue, maintain and verify certificates;
4. provide Pro features, create and manage subscriptions, reconcile payments and respond to payment events;
5. enable organisation assessments and provide results to the relevant organisation;
6. respond to questions, complaints, refund requests and support needs;
7. protect the Services, prevent fraud and abuse, investigate incidents and enforce our Terms;
8. maintain backups, troubleshoot errors, understand reliability and improve the Services; and
9. comply with legal obligations and establish, exercise or defend legal claims.

Where consent is required by applicable law, we will seek it and provide a way to withdraw it. Withdrawing consent may prevent us from providing a feature that requires the relevant information, but will not invalidate processing already carried out lawfully.

## 4. Cookies, sessions and local storage

TypeFlow uses necessary technologies to authenticate users, maintain sessions, protect requests, remember relevant application state and keep the Services secure. Your browser may also store information needed for a user-initiated workflow, such as continuing an account or certificate claim.

Blocking or deleting necessary cookies or storage may prevent login or some features from working. If we add analytics, advertising or other optional tracking technologies, we will update this Policy and obtain consent where required by law.

## 5. When we share information

We do not sell your personal information as a standalone data product. We may share information only as reasonably needed for the purposes described in this Policy, including with:

- **Supabase** for authentication and database services;
- **Vercel** for hosting, deployment, request handling and related service logs;
- **Razorpay** for payment processing, subscription management and related notifications;
- other infrastructure, security, communications or support providers used to operate the Services;
- an organisation that invited you to an assessment, as needed to provide that assessment and its results; and
- public certificate-verification visitors, but only for the details made visible on the applicable verification page.

We may also disclose information to a competent authority or adviser where reasonably necessary to comply with law, protect safety or rights, investigate fraud, or handle a dispute. If TypeFlow undergoes a business transfer, information may be transferred as part of that transaction subject to appropriate safeguards and applicable law.

Service providers may process data in locations outside the state or country where you are located. Any cross-border processing will be subject to provider configuration and applicable law.

## 6. Organisation assessments

When an organisation administers an assessment, it may provide candidate information to TypeFlow and receive assessment status or results. The organisation is responsible for determining its purposes and providing candidate notices or obtaining permissions required for its use of that information. If you have questions about how an employer or other organisation uses your result after receiving it, you may need to contact that organisation directly as well as TypeFlow.

## 7. Retention

We retain information for as long as reasonably necessary to provide the Services, maintain account and certificate integrity, manage subscriptions and disputes, provide support, protect security, comply with legal obligations and maintain records required by law.

Different data may have different retention periods. For example, account information may remain while an account is active; payment and subscription references may be retained for reconciliation and legal/accounting needs; security logs may be retained for a shorter operational period; and certificate verification records may need to remain available to validate certificates already issued.

You may request account deletion or erasure of personal information, subject to applicable law, legitimate security needs, unresolved transactions, dispute handling, and information that must or may lawfully be retained. Deleting an account may disable associated services, certificates or assessment history. We will explain any material limitation when responding to a request.

## 8. Your choices and requests

You can ask us to:

- confirm whether we process personal information about you;
- correct information that is inaccurate or incomplete;
- delete information where applicable law gives you that right and retention is not otherwise required or permitted;
- withdraw consent where processing is based on consent;
- explain a privacy concern or make a grievance; and
- help you access account information through available account controls.

Email **xvshad585@gmail.com** from the address associated with your account and explain your request. We may ask for reasonable information to verify your identity. Do not send passwords, one-time passcodes, full card details or authentication tokens. We will respond within the timelines required by applicable law and otherwise aim to respond promptly.

## 9. Children and age-related information

Paid subscriptions are intended for adults who can enter into a binding agreement under applicable law. If an organisation uses TypeFlow for participants under 18, it must ensure that the required legal authority, notices and consent arrangements are in place before submitting or requesting processing of their personal information. Contact us before using TypeFlow for a child-focused programme. We will update our age and consent procedures as applicable data-protection requirements come into force.

## 10. Security

We use reasonable technical and organisational safeguards designed to protect information, including access controls, authentication, validation, logging and controlled handling of payment-related events. No online service can guarantee absolute security. Keep your credentials private and tell us promptly if you believe your account is compromised.

If we identify a data incident, we will investigate and take actions required by applicable law, which may include notifications to affected people or authorities.

## 11. Third-party websites and services

Payment providers, organisation platforms and linked websites have their own terms and privacy policies. We are not responsible for independent processing by third parties outside our control. Review the relevant provider’s terms when you use its service.

## 12. Changes to this Policy

We may update this Policy when the Services, providers, processing activities or legal requirements change. The date at the top indicates the latest revision. If a change materially affects how we use personal information, we will give notice or seek consent where required.

## 13. Contact and grievances

For privacy questions or requests, contact **xvshad585@gmail.com**. The operator should verify that the email is correctly spelled and monitored before publication. The Contact & Grievance Redressal page provides further contact and complaint information.

---

**Implementation note:** This is a privacy-policy draft, not a substitute for a data inventory or legal review. Before publication, confirm which logs/traces are actually stored, the precise certificate-verification fields, provider hosting regions, retention rules, and whether the product will allow minors to use the Services. The Digital Personal Data Protection Act and Rules have phased commencement; build the required notice, consent, withdrawal and rights workflows before the relevant provisions apply.
`;
